const INCREMENT_LEVEL = 'INCREMENT_LEVEL';
const SET_CARD_LIST = 'SET_CARD_LIST';
const INSERT_MATCHED_ITEM = 'INSERT_MATCHED_ITEM';
const SET_FIRST_SELECTION = 'SET_FIRST_SELECTION';
const INCREMENT_TIMER = 'INCREMENT_TIMER';
const SET_SECOND_SELECTION = 'SET_SECOND_SELECTION'

export {
    INCREMENT_LEVEL,
    SET_CARD_LIST,
    INSERT_MATCHED_ITEM,
    SET_FIRST_SELECTION,
    INCREMENT_TIMER,
    SET_SECOND_SELECTION,
};
